### ISSUE TITLE
Subsample of dataset

### ISSUE THREAD

**Issue by dyahadila** [MIT-LCP/mimic-cxr#9]
Hello, is it possible to download just a subset of the dataset? This is to browse through the data first, since investing in 4.7 TB is quite a lot.

**Comment by alistairewj** [comment]
We've been thinking about a demo but haven't made one yet since we have yet to decide which patients to include. For now I'd suggest one of two things: first you can view the DICOM files and the text files via PhysioNet if that helps. Alternatively it's pretty easy to download just a subset once you get `gsutil` working, something like:

`gsutil -m cp -r gs://mimic-cxr-2.0.0.physionet.org/files/p10/p10000032 ./`

.. which downloads all the DICOMs for a single patient (100 MB) and

`gsutil -m cp -r gs://mimic-cxr-2.0.0.physionet.org/files/p10/p10000* ./`

... which downloads the DICOMs for 4 patients (500 MB).

There's some instructions on gsutil on the website: https://mimic-cxr.physionet.org/about/download/

**Comment by dyahadila** [comment]
Thank you!
